// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5TW-PbZbAWVwN7PriSzZ5hPchpt99P4',
    appId: '1:945587661616:web:7f470b107c4347f1cfb6f5',
    messagingSenderId: '945587661616',
    projectId: 'codeapp-5de8d',
    authDomain: 'codeapp-5de8d.firebaseapp.com',
    storageBucket: 'codeapp-5de8d.firebasestorage.app',
    measurementId: 'G-6PGNQMHYTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWXl7RDCw2iMJFS9uRWdAxTngNsXtoylk',
    appId: '1:945587661616:android:904e43b70902ed9ecfb6f5',
    messagingSenderId: '945587661616',
    projectId: 'codeapp-5de8d',
    storageBucket: 'codeapp-5de8d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh5TW-PbZbAWVwN7PriSzZ5hPchpt99P4',
    appId: '1:945587661616:web:af5ae52ab08b9c26cfb6f5',
    messagingSenderId: '945587661616',
    projectId: 'codeapp-5de8d',
    authDomain: 'codeapp-5de8d.firebaseapp.com',
    storageBucket: 'codeapp-5de8d.firebasestorage.app',
    measurementId: 'G-EDE95MM3TE',
  );
}
